### ISSUE TITLE
Cannot run capybara tests locally

### ISSUE THREAD

**Issue by LinqLover** [hpi-swt2/contacts-portal#121]
```
$ bundle exec rspec spec/features/navbar_spec.rb 
Capybara starting Puma...
* Version 5.0.4 , codename: Spoony Bard
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:27402
FF[...]

Failures:

  1) Navbar profile dropdown is not expanded by default
     Failure/Error: visit root_path
     
     Selenium::WebDriver::Error::UnknownError:
       Process unexpectedly closed with status 0
     # ./spec/features/navbar_spec.rb:8:in `block (2 levels) in <top (required)>'

  2) Navbar profile dropdown expands after being clicked on
     Failure/Error: visit root_path
     
     Selenium::WebDriver::Error::UnknownError:
       Process unexpectedly closed with status 0
     # ./spec/features/navbar_spec.rb:8:in `block (2 levels) in <top (required)>'

  [...]

Finished in 31.48 seconds (files took 4.59 seconds to load)
7 examples, 7 failures

Failed examples:

rspec ./spec/features/navbar_spec.rb:12 # Navbar profile dropdown is not expanded by default
rspec ./spec/features/navbar_spec.rb:17 # Navbar profile dropdown expands after being clicked on
[...]

Coverage report generated for RSpec to /path/to/connections-portal/coverage. 23 / 201 LOC (11.44%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

Changing `$DISPLAY` to `:5` doesn't help either. I'm in a headless WSL environment which was not a problem earlier ...

**Comment by felixauringer** [comment]
> I'm in a headless WSL environment which was not a problem earlier ...

We now use javascript in our project and therefore had to include a headless Browser in our tests which apparently does not work well with WSL

**Comment by felixauringer** [comment]
@LinqLover I don't want to spam Discord so I reply here:  
Vagrant is a manager for virtual machines that uses VirtualBox in the Background. The tests with a headless firefox work without problems in a VM created by our Vagrantfile. I'm not sure if Vagrant works good with Windows but it's worth a try because the setup is really easy. Nevertheless I would recommend using Windows for developing ;)

**Comment by LinqLover** [comment]
Thanks for the pointer. I will try that out when I need it the next time ... Unfortunately, installing dev stuff directly in Windows is not that easy as installing it in Linux/WSL, and Vagrant sounds a quite heavy (i.e. resources-extensive) tool ... :-)

**Comment by felixauringer** [comment]
I do not think that headless VirtualBox VM are really resource-extensive:  
![image](https://user-images.githubusercontent.com/48409110/104760022-10c93c80-5761-11eb-8dbc-a01bd20418af.png)
2% of my RAM are aproximately 640MB and there is only real CPU load when the server responds to a request / runs a test. That's definitely less than RubyMine :sweat_smile:  
But I think you mentioned the reason why Linux is better for developing than Windows ;)

**Comment by LinqLover** [comment]
Well, 640 MB *is* a lot of RAM - a VS Code window only consumes half as much space. But that's probably out of topic. :-)

So will we leave this ticket open until the installation instructions in the `README.md` are again correctly (which do not mention the setup of any x-server solution ATM)?

**Comment by felixauringer** [comment]
> So will we leave this ticket open until the installation instructions in the `README.md` are again correctly (which do not mention the setup of any x-server solution ATM)?

The setup just assumes that Linux is used because it is most common but feel free to add any Windows specific requirements after you figured them out :)
